imports:
    - { resource: roles.yaml }

security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    providers:
        in_memory:
            memory: ~
        main:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bundles|assets|build)/
            security: false

        main:
            anonymous: ~
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 2592000
                path:     /
                domain:   ~
                secure: true
            pattern:    ^/
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_user }
            user_checker: faros_user.user_checker
            guard:
                authenticators:
                    - faros_admin.login_form_authenticator
            logout:
                path:   admin_logout
                target: admin_login
                invalidate_session: false
            provider: main

    access_control:
        - { path: ^/translations, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, role: ROLE_ADMIN }
