ansistrano_git_repo: <git_repository>
ansible_ssh_common_args: " -o ForwardAgent=yes"
lephare_sentry_project: <sentry_project>
lephare_http_basic_user: <admin_user>
lephare_http_basic_password: <admin_password>

db_pull_local_database_host: <local_database_host>
db_pull_local_database_name: <local_database_name>
db_pull_local_database_user: <local_database_user>
db_pull_local_database_password: <local_database_password>
