imports:
    - { resource: roles.yaml }

security:
    # hide_user_not_found: false # true by default, if set to false will show "locked" or "not found" user error

    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # users_in_memory: { memory: null }
        main:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|bundles|assets|build)/
            security: false
        main:
            provider: main
            user_checker: "faros_user.user_checker"
            pattern: ^/
            form_login:
                username_parameter: email
                password_parameter: password
                login_path: admin_login
                check_path: admin_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                role: switch_user

            # https://symfony.com/doc/current/security.html#limiting-login-attempts
            login_throttling:
                max_attempts: 10
                interval: "3 minutes"

    access_control:
        - { path: ^/translations, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/, role: ROLE_ADMIN }
