---
- name: Create symfony private key from ansible vault
  hosts: app
  vars_files:
    - _variables.yml
  tasks:
    - name: Write symfony private key
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "../config/secrets/{{ symfony_env }}/{{ symfony_env }}.decrypt.private.php"
        mode: "0600"
        content: |
            <?php // {{ symfony_env }}.decrypt.private on {{ ansible_date_time.iso8601 }}

            // SYMFONY_DECRYPTION_SECRET={{ symfony_secret_private_key | b64encode }}
            return "{{ symfony_secret_private_key }}";
