faros_event_log:
    event_log_transaction_class: App\Entity\EventLog\Transaction
    event_log_log_class: App\Entity\EventLog\Log
    event_log_tag_class: App\Entity\EventLog\Tag

doctrine:
    dbal:
        types:
            event_log_status: Faros\Component\EventLog\Types\EventLogStatusType

monolog:
    channels: ['faros_event_log']
    handlers:
        faros_event_log_buffer:
            type: buffer
            handler: event_log_dbal_handler
            channels: [ "faros_event_log" ]
            level: debug
        event_log_dbal_handler:
            type: service
            id: "faros_event_log.doctrine_handler"
            level: debug
            channels: [ "faros_event_log" ]
