security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_ADMIN:
            - ROLE_ADMIN_LOGIN
            - ROLE_ADMIN_USER
            - ROLE_ADMIN_GROUP
            - ROLE_ADMIN_ACTION
            - ROLE_ADMIN_MEDIA

imports:
    - { resource: "@FarosAdminBundle/Resources/config/role/core.yml" }
    - { resource: "@FarosAdminBundle/Resources/config/role/elfinder.yml" }
    - { resource: "@FarosAdminBundle/Resources/config/role/seo.yml" }
