services:
    php:
        image: lephare/php:8.4
        init: true
        volumes:
            - ./:/var/www/symfony
            - ${COMPOSER_HOME:-~/.composer}:/tmp/composer
        environment:
            COMPOSER_HOME: /tmp/composer
            DOCKER_HOST_SUFFIX: ${DOCKER_HOST_SUFFIX:-local}
            SYMFONY_DEPRECATIONS_HELPER: "max[direct]=0&verbose=1"
        networks:
            - default
            - private

    web:
        image: lephare/apache:2.4
        networks:
            - default
            - public
        volumes_from:
            - php:ro
        labels:
            caddy: 'project.${DOCKER_HOST_SUFFIX:-local}'
            caddy.tls: internal
            caddy.reverse_proxy: '{{ upstreams }}'
        environment:
            DOCUMENT_ROOT: /var/www/symfony/public

networks:
    private:
        external: true
        name: dev_private
    public:
        external: true
        name: dev_public
